base/urls.py
from base import views, userManagement, menus
from django.urls import path

urlpatterns = [
    path('adduser', userManagement.add_user),
    path('menuedit', menus.menu_edit),
    path('queryregion', views.queryRegion),
    path('keyboard', views.keyboard),

]

main/urls.py
from base import views
from base.views import page_error, page_not_found, permission_denied
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from django.views.generic.base import RedirectView
# from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_view),

    path('captcha', include('captcha.urls')),

    path('base/', include('base.urls')),

    path('elementary/', include('elementary.urls')),

    path('supports/', include('supports.urls')),

    path('login/', views.login_view),
    path('logout/', views.logout_view, name='logout'),
    path('index/', views.index_view, name='index'),

]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler403 = permission_denied
handler404 = page_not_found
handler500 = page_error

elementary/models.py
from django.db import models
from base.models import region
# from mdeditor.fields import MDTextField


class basiceduchoices():
    stuobj = (
        (1, '户籍所在地属于划片范围内的适龄人员'),
        (2, '外省外县进城务工随迁子女（家长务工就业或经商）'),
        (3, '盘州市内进城务工子女（家长务工就业或经商）'),
        (4, '烈士子女、驻盘部队的现役军人子女、公安英模和因公牺牲、伤残警察子女'),
        (5, '参加抗疫最前线的医护人员的子女'),
        (6, '易地扶贫搬迁子女'),
    )
    operator = (
        (0, '未上传资料或未提交'),
        (1, '提交待初审'),
        (2, '初审通过'),
        (3, '审核不通过（不允许再次提交）'),
        (4, '审核不通过（驳回修改)'),
        (5, '复审通过'),
        (6, '复审不通过'),
    )
    houseoptions = (
        (0, '购房'),
        (1, '租房'),
        (2, '自建房'),
    )
    relations = (
        (1, '无'),
        (2, '父亲'),
        (3, '母亲'),
        (4, '爷爷'),
        (5, '奶奶'),
        (6, '外公'),
        (7, '外婆'),
        (12, '亲哥'),
        (13, '亲嫂'),
        (14, '表哥'),
        (15, '表嫂'),
        (16, '堂哥'),
        (17, '堂嫂'),
        (18, '亲姐'),
        (19, '亲姐夫'),
        (20, '表姐'),
        (21, '表姐夫'),
        (22, '堂姐'),
        (23, '堂姐夫'),
        (24, '伯父'),
        (25, '伯母'),
        (26, '叔父'),
        (27, '婶母'),
        (28, '舅父'),
        (29, '舅母'),
        (30, '姨父'),
        (31, '姨母'),
        (32, '姑父'),
        (33, '姑母'),
        (34, '其他亲属'),
        (35, '非亲属'),
    )


class stu_grades(models.Model):
    id = models.PositiveSmallIntegerField(verbose_name='年级', primary_key=True)
    name = models.CharField(max_length=50, verbose_name='年级名称')

    class Meta:
        verbose_name = '年级名称表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class stu_schools(models.Model):
    id = models.PositiveSmallIntegerField(verbose_name='学校编号', primary_key=True)
    name = models.CharField(max_length=50, verbose_name='学校名称')

    class Meta:
        verbose_name = '学校名称表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class stu_school_grade(models.Model):
    id = models.PositiveSmallIntegerField(verbose_name='序号', primary_key=True)
    school = models.ForeignKey(stu_schools, null=True, db_constraint=False,
                               related_name='schoolname', on_delete=models.SET_NULL)
    grade = models.ForeignKey(stu_grades, null=True, db_constraint=False, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = '学校年级名称总表'
        verbose_name_plural = verbose_name
        unique_together = ['school', 'grade']

    def __str__(self):
        return self.school.name + self.grade.name


class stu_register_table(models.Model):
    id = models.AutoField(
        primary_key=True)
    name = models.CharField(
        max_length=20, null=True, unique=False, verbose_name='学生姓名')
    card = models.CharField(
        max_length=18, null=True, unique=False, verbose_name='学生身份证号')
    age = models.IntegerField(
        null=True, verbose_name='年龄')
    schoolGrade = models.ForeignKey(
        stu_school_grade, null=True, db_constraint=False,
        on_delete=models.SET_NULL)
    jfr1name = models.CharField(
        max_length=20, null=True, unique=False, verbose_name='监护人1姓名')
    jfr1gx = models.PositiveSmallIntegerField(
        verbose_name='监护人1与登记人关系', choices=basiceduchoices.relations)
    jfr1tel = models.CharField(
        max_length=11, null=True, unique=False, verbose_name='监护人2联系电话')
    jfr2name = models.CharField(
        max_length=20, null=True, unique=False, verbose_name='监护人2姓名')
    jfr2gx = models.PositiveSmallIntegerField(
        verbose_name='监护人2与登记人关系',
        choices=basiceduchoices.relations, null=True)
    jfr2tel = models.CharField(
        max_length=11, null=True, unique=False, verbose_name='监护人2联系电话')
    regaddress = models.ForeignKey(
        region, null=True, db_constraint=False,
        on_delete=models.SET_NULL,
        related_name='reg', verbose_name='户籍所在地')
    resaddress = models.ForeignKey(
        region, null=True, db_constraint=False,
        on_delete=models.SET_NULL,
        related_name='res', verbose_name='居住所在地')
    resaddressnum = models.CharField(
        max_length=100, null=True, unique=False, verbose_name='居住地详细地址')
    stuobj = models.PositiveSmallIntegerField(
        verbose_name='登记对象属性', choices=basiceduchoices.stuobj)
    houseoption = models.PositiveSmallIntegerField(
        verbose_name='预登记学生现住房类型', choices=basiceduchoices.houseoptions)
    operatortype = models.IntegerField(
        '操作状态', default=0, choices=basiceduchoices.operator)
    publicid = models.IntegerField(
        '是否公示', default=0)

    class Meta:
        verbose_name = '预登记情况总表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class operation_stu_log(models.Model):
    card = models.CharField(
        max_length=18, null=True, unique=False, verbose_name='学生身份证号')
    edittype = models.IntegerField(
        '操作状态', default=0, choices=basiceduchoices.operator)
    names = models.CharField(
        max_length=11, null=True, unique=False, verbose_name='操作人')
    times = models.CharField(
        max_length=20, null=True, unique=False, verbose_name='操作时间')
    result = models.CharField(
        max_length=100, null=True, unique=False, verbose_name='操作结果')
    resultnotes = models.CharField(
        max_length=200, null=True, unique=False, verbose_name='操作情况补充说明')

    class Meta:
        verbose_name = '预登记情况操作日志'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.names


class infant_stu(models.Model):
    id = models.AutoField(
        primary_key=True)
    name = models.CharField(
        max_length=20, null=True, unique=False, verbose_name='学生姓名')
    card = models.CharField(
        max_length=18, null=True, unique=False, verbose_name='学生身份证号')
    age = models.IntegerField(
        '年龄')
    regaddress = models.CharField(
        max_length=100, null=True, unique=False, verbose_name='户籍所在地')
    resaddress = models.CharField(
        max_length=100, null=True, unique=False, verbose_name='居住所在地')
    regsch = models.CharField(
        max_length=100, null=True, unique=False, verbose_name='意向学校')
    tel = models.CharField(
        max_length=11, null=True, unique=False, verbose_name='联系电话')

    class Meta:
        verbose_name = '幼儿园入学意向调查表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

base/views.py
import os
import json
import time
import ast
from django.http import HttpResponse, FileResponse
from django.views.decorators.cache import cache_page
from django.core.mail import EmailMessage
# from django.core.mail import send_mail
from django.conf import settings
from django.shortcuts import render, HttpResponse, redirect
# from django.views.decorators import csrf
from django.contrib import auth
from django.contrib.auth import authenticate, login
from django import forms
from django.http import JsonResponse
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth.models import Group
from django.db.models import Q, F
from django.views.decorators.csrf import csrf_exempt

from captcha.fields import CaptchaField, CaptchaStore

from base import menus
from base import mytools
from base.models import userBase, region


class UserForm(forms.Form):
    captcha = CaptchaField(label='验证码', required=True,
                           error_messages={'required': '验证码不能为空'})


def index_view(request):
    status = request.COOKIES.get('is_login')
    if not status:
        return redirect("/login/")
    if not request.user.is_authenticated:
        return redirect("/login/")
    ctx = {}
    menu = menus.main_menu(request.user)
    ctx['dic'] = {"menu": menu}
    return render(request, "index.html", ctx)


def login_view(request):
    register_form = UserForm(request.POST)
    if register_form.is_valid():
        pass
    register_form = UserForm()
    if request.method == "GET":
        return render(request, "login.html", {'register_form': register_form})
    username = request.POST.get("username")
    password = request.POST.get("pswd")
    key = request.POST.get("captcha_0")
    code = request.POST.get("captcha_1")
    captcha_obj = CaptchaStore.objects.filter(hashkey=key).values().count()
    user = authenticate(username=username, password=password)
    if user and captcha_obj != 1:
        auth.login(request, user)
        rep = redirect("/index/")
        rep.set_signed_cookie("is_login", user, salt='is_login_jmy',
                              max_age=60*30)
        rep.user = user
        return rep
    else:
        users = userBase.objects.filter(username=username,
                                        is_active=False).values()
        if users.exists():
            return render(request, "login.html",
                          {'msg': '用户未激活，请登录注册邮箱激活!',
                           'register_form': register_form}
                          )
        else:
            return render(request, "login.html",
                          {'msg': '请核实用户名、密码、验证码',
                           'register_form': register_form}
                          )


def logout_view(request):
    auth.logout(request)
    rep = redirect('/login/')
    rep.delete_cookie("is_login")
    request.session.flush()
    return rep


def active(request, parameter):
    try:
        jm = mytools.AEScoder()
        aes = jm.decrypt(parameter)
    except Exception:
        return redirect("/login/")
    else:
        user_dict = ast.literal_eval(aes)
        username = user_dict['user']
        mytime = float(user_dict['time'])
        nowtime = float(time.time())
        mytime = int((nowtime - mytime) / 3600)
        ctx = {}
        if mytime <= 1:
            user = userBase.objects.get(username=username)
            user.is_active = True
            user.save()
            ctx['msg'] = "用户激活成功！"
        else:
            ctx['msg'] = "链接已失效!"
        return render(request, 'base/msg.html', ctx)


def msg(request):
    return render(request, 'base/msg.html')


def register(request):
    if request.method == 'POST':
        username = request.POST['user']
        first_name = request.POST['name']
        card = request.POST['card']
        phone = request.POST['tel']
        email = request.POST['email']
        message = request.POST['message']
        password = make_password(request.POST['pwd'])
        group = request.POST['group']
        usercreate = userBase.objects.create(
                username=username, first_name=first_name,
                card=card, phone=phone, email=email,
                message=message, password=password)
        usercreate.is_active = 0
        usercreate.save()
        if group == '1':
            pass
        elif group == '5':
            print(group)
            g = Group.objects.get(name='教学质量组')
            g.user_set.add(usercreate)
        else:
            pass
        if usercreate:
            oldstr = {'user': usercreate.username,
                      'time': str(time.time())
                      }
            jm = mytools.AEScoder()
            aes = jm.encrypt(oldstr)
            subject = "用户激活"
            message = '''<h1>{}, 欢迎您</h1>请点击下面链接激活您的账户<br/>
            <a href="https: //218.201.223.229: 8888/active/{}">点我激活</a></br>
            https: //218.201.223.229: 8888/active/{}
            '''.format(first_name, aes, aes)
            sender = settings.EMAIL_FROM
            receiver = [email]
            msg = EmailMessage(subject, message, sender, receiver)
            msg.content_subtype = 'html'
            msg.send()
            return redirect("/login/")
    else:
        return render(request, 'register.html')


def forget(request):
    if request.method == 'POST':
        username = request.POST['user']
        card = request.POST['card']
        phone = request.POST['tel']
        email = request.POST['email']
        password = make_password(request.POST['pwd'])
        user = userBase.objects.filter(
                username=username, card=card, phone=phone, email=email).first()
        if user:
            user.password = password
            user.save()
            return redirect("/login/")
        else:
            return redirect("/login/")
    else:
        return render(request, 'forget.html')


def checkUser(request):
    user = request.POST['user']
    result = userBase.objects.filter(username=user)
    if result.exists():
        return JsonResponse({'msg': 'yes'})
    else:
        return JsonResponse({'msg': 'no'})


def page_not_found(request, exception):
    return render(request, 'base/404.html')


def page_error(request):
    return render(request, 'base/500.html')


def permission_denied(request, exception):
    return render(request, 'base/403.html')


def file_response_download(request):
    file_path = 'media/' + request.GET.get('file_path')
    response = FileResponse(open(file_path, 'rb'))
    response['content_type'] = "application/octet-stream"
    response['Content-Disposition'] = 'attachment; filename='\
        + os.path.basename(file_path)
    return response


def help_webs(request):
    ctx = {}
    table_title = ['类别', '网站名称', '网址']
    ctx['dic'] = {"url": "help_webs/",
                  "name": "学校名称", "card": "学校标识码", "mytitle": "",
                  "table_title": table_title}
    return render(request, "base/webs.html", ctx)


def help_webs_ajax(request):
    pageNumber = request.POST['pageNumber']
    pageSize = request.POST['pageSize']
    p1 = request.POST['PA1']
    webs = {}
    mydata = webs.objects.filter(Q(category__contains=p1)).values()
    total = mydata.count()
    rows = list(mydata)
    resList = {"total": total, "rows": rows}
    ulist = json.dumps(resList, ensure_ascii=False)
    return HttpResponse(ulist)


def schoolBase(request):
    name = request.GET.get('pa1', '')
    township = request.GET.get('pa2', '0')
    period = request.GET.get('pa3', '0')
    pageNumber = request.GET.get('pageNumber', 1)
    pageSize = request.GET.get('pageSize', 30)
    from analysis.models import schoolBase
    from django.core.paginator import Paginator
    if township == '0':
        if period == '0':
            data = schoolBase.objects.filter(name__contains=name)
        else:
            data = schoolBase.objects.filter(
                    name__contains=name, township=township)
    else:
        if period == '0':
            data = schoolBase.objects.filter(
                    name__contains=name, township=township)
        else:
            data = schoolBase.objects.filter(
                    name__contains=name, township=township, period=period)
    paginator = Paginator(data, pageSize)
    page_data = paginator.get_page(pageNumber)
    data = page_data.object_list
    ctx = {
        'data': data,
        'title': mytools.mychoices.titlebaseschool,
        'total': paginator.count,
        'pageNumber': pageNumber,
        'pageSize': pageSize,
        'township': mytools.mychoices.township,
        'period': mytools.mychoices.period,
        'pas': '?pa1=' + name + "&pa2=" + township + "&pa3=" + period,
        'oldpa': [name, township, period]
        }
    return render(request, "base/base_school.html", ctx)


@csrf_exempt
@cache_page(24*60*60)
def queryRegion(request):
    pid = request.GET.get('pid')
    level = request.GET.get('level')
    mid = request.GET.get('mid', '')
    if level == '1':
        data = region.objects.filter(level=level).values(
                'pid', 'level', 'addressAll',
                text=F('addressShort'), id=F('mid'))
    elif mid != "":
        data = region.objects.filter(mid=mid+"000000").values(
                'pid', 'level', 'addressAll',
                text=F('addressShort'), id=F('mid'))
    else:
        data = region.objects.filter(pid=pid, level=level).values(
                'pid', 'level', 'addressAll',
                text=F('addressShort'), id=F('mid'))
    mydata = json.dumps(list(data))
    return HttpResponse(mydata)


def keyboard(request):

    return render(request, 'base/keyboard.html')


def page_not_found(request, exception):
    return render(request, 'base/404.html')


def page_error(request):
    return render(request, 'base/500.html')


def permission_denied(request, exception):
    return render(request, 'base/403.html')


def file_response_download(request):
    file_path = 'media/' + request.GET.get('file_path')

templates/base/adduser.html
{% extends "base.html" %}
{% block mainbody %}
<table class="easyui-datagrid">
  <thead>
    <tr>
      <th data-options="field:'id'">id</th>
      <th data-options="field:'username'">登录名</th>
      <th data-options="field:'first_name'">用户简称</th>
      <th data-options="field:'last_name'">用户全称</th>
      <th data-options="field:'email'">电子邮箱</th>
      <th data-options="field:'nick_name'">所在单位</th>
      <th data-options="field:'birday'">生日</th>
      <th data-options="field:'address'">家庭住址</th>
      <th data-options="field:'mobile'">联系电话</th>
      <th data-options="field:'is_superuser'">是否系统管理员</th>
      <th data-options="field:'is_staff'">是否工作用户</th>
      <th data-options="field:'is_active'">账户启用状态</th>
      <th data-options="field:'last_login'">上次登录时间</th>
      <th data-options="field:'date_joined'">账户创建时间</th>
      <th data-options="field:'image'">头像</th>
    </tr>
  </thead>
  <tbody>
    {% for i in mydata %}
    <tr>
      <td>{{i.id}}</td>
      <td>{{i.username}}</td>
      <td>{{i.first_name}}</td>
      <td>{{i.last_name}}</td>
      <td>{{i.email}}</td>
      <td>{{i.nick_name}}</td>
      <td>{{i.birday}}</td>
      <td>{{i.address}}</td>
      <td>{{i.mobile}}</td>
      <td>{{i.is_superuser}}</td>
      <td>{{i.is_staff}}</td>
      <td>{{i.is_active}}</td>
      <td>{{i.last_login}}</td>
      <td>{{i.date_joined}}</td>
      <td>{{i.image}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock mainbody %}

templates/base/forget.html
{% extends "base.html" %}
{% block mainbody %}
kkkk
{% endblock mainbody %}

templates/base/keyboard.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="css/style.css" rel="stylesheet">
  </head>
  <body>
 hello world 
  </body>
</html>

templates/base/menuedit.html
{% extends "base.html" %}
{% block mainbody %}
<table class="easyui-datagrid">
  <thead>
    <tr>
      <th data-options="field:'id'">id</th>
      <th data-options="field:'melement'">element</th>
      <th data-options="field:'mhref'">href</th>
      <th data-options="field:'msrc'">src</th>
      <th data-options="field:'mclass'">class</th>
      <th data-options="field:'mdataoption'">dataoption</th>
      <th data-options="field:'mtitle'">title</th>
      <th data-options="field:'mstyle'">mstyle</th>
      <th data-options="field:'level'">level</th>
      <th data-options="field:'pid'">pid</th>
      <th data-options="field:'mid'">mid</th>
    </tr>
  </thead>
  <tbody>
    {% for i in mydata %}
    <tr>
      <td>{{i.id}}</td>
      <td>{{i.melement}}</td>
      <td>{{i.mhref}}</td>
      <td>{{i.msrc}}</td>
      <td>{{i.mclass}}</td>
      <td>{{i.mdataoption}}</td>
      <td>{{i.mtitle}}</td>
      <td>{{i.mstyle}}</td>
      <td>{{i.level}}</td>
      <td>{{i.pid}}</td>
      <td>{{i.mid}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock mainbody %}
{%  block js %}

{% endblock js %}

templates/base/pagenum.html
{% extends "base.html" %}
{% load static %}
{% block mainbody %}
<div data-options="region:'center'" style="background:#eee;">
  <table>
    <thead>
      {% for item in title %}
      <th>{{item}}</th>
      {% endfor %}
    </thead>
    {% for item in data %}
    <tr>
      <td>{{forloop.counter}}</td>
      <td>{{item.name}}</td>
      <td>{{item.card}}</td>
      <td>{{item.age}}</td>
      <td>{{item.get_schobj_display}}</td>
      <td>{{item.jfr1name}}</td>
      <td>{{item.get_jfr1gx_display}}</td>
      <td>{{item.jfr1tel}}</td>
      <td>{{item.jfr2name}}</td>
      <td>{{item.get_jfr2gx_display}}</td>
      <td>{{item.jfr2tel}}</td>
      <td>{{item.regaddress}}</td>
      <td>{{item.resaddress}}</td>
      <td>{{item.resaddressnum}}</td>
      <td>{{item.get_regsch_display}}</td>
      <td>{{item.get_stuobj_display}}</td>
      <td>{{item.get_houseoption_display}}</td>
      <td>{{item.get_operatortype_display}}</td>
      <td>{{item.publicity}}</td>
      <td>
	<a id="btn" href="stuexamine?pa={{item.card}}" target="_blank" class="easyui-linkbutton" data-options="iconCls:'icon-edit'">审核</a>
      </td>
    </tr>
    {% endfor %}
  </table>
  <input id="pas" type="" value="{{pas}}" hidden>
</div>
<div data-options="region:'south'," style="height:35px;">
  <div id="pp" class="easyui-pagination" style="background:#efefef;border:1px solid #ccc;" data-options="total:{{total}},pageNumber:{{pageNumber}},pageSize:{{pageSize}}"> </div>
</div>
{% endblock mainbody %}
{% block myjs %}
<style>
table tr td { border:1px solid #000; }
table thead th { border:1px solid #000; }
table { text-align: center; border-collapse: collapse; padding:2px;}
</style>
<script>
  $('#pp').pagination({
      onSelectPage:function(pageNumber, pageSize){
	  let thisURL=window.location.pathname;
	  let pas=$('#pas').val();
	  console.log(pas);
	  window.location.href=thisURL + pas + "&pageSize=" + pageSize + "&pageNumber=" + pageNumber;
	}
    });
</script>
{% endblock myjs %}