base/urls.py
from base import views, userManagement, menus
from django.urls import path

urlpatterns = [
    path('adduser', userManagement.add_user),
    path('menuedit', menus.menu_edit),
    path('queryregion', views.queryRegion),
    path('keyboard', views.keyboard),

]

elementary/urls.py
from elementary.views import *
from django.urls import path

urlpatterns = [
    path('Review/Index', ReviewIndex.as_view(), name='review_index'),
    path('Review/StuInfo', ReviewStuInfo.as_view(), name='review_stuInfo'),
    path('Review/SeeImage', ReviewSeeImage, name='review_see_image'),
    path('Review/Gather', ReviewGather.as_view(), name='reaview_gather'),

    path('stu/index', stuIndex, name='stu_index'),
    path('stu/checkuser', checkUser, name='stu_check_user'),
    path('stu/Register', stuRegister.as_view(), name='stu_register'),
    path('stu/QueryRegister', stuQueryRegister, name='stu_query_register'),
    path('stu/publicity', publicitys, name='stu_publicity'),
    path('stu/UploadImage', stuUploadImage.as_view(), name='stu_upload_image'),

    path('stu/keyboardpiano', keyboardsPiano, name='keyboardPiano'),

]

main/urls.py
from base import views
from base.views import page_error, page_not_found, permission_denied
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from django.views.generic.base import RedirectView
# from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_view),

    path('captcha', include('captcha.urls')),

    path('base/', include('base.urls')),

    path('elementary/', include('elementary.urls')),

    path('supports/', include('supports.urls')),

    path('login/', views.login_view),
    path('logout/', views.logout_view, name='logout'),
    path('index/', views.index_view, name='index'),

]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler403 = permission_denied
handler404 = page_not_found
handler500 = page_error

elementary/models.py
from django.db import models
from base.models import region
# from mdeditor.fields import MDTextField


class basiceduchoices():
    stuobj = (
        (1, '户籍所在地属于划片范围内的适龄人员'),
        (2, '外省外县进城务工随迁子女（家长务工就业或经商）'),
        (3, '盘州市内进城务工子女（家长务工就业或经商）'),
        (4, '烈士子女、驻盘部队的现役军人子女、公安英模和因公牺牲、伤残警察子女'),
        (5, '参加抗疫最前线的医护人员的子女'),
        (6, '易地扶贫搬迁子女'),
    )
    operator = (
        (0, '未上传资料或未提交'),
        (1, '提交待初审'),
        (2, '初审通过'),
        (3, '审核不通过（不允许再次提交）'),
        (4, '审核不通过（驳回修改)'),
        (5, '复审通过'),
        (6, '复审不通过'),
    )
    houseoptions = (
        (0, '购房'),
        (1, '租房'),
        (2, '自建房'),
    )
    relations = (
        (1, '无'),
        (2, '父亲'),
        (3, '母亲'),
        (4, '爷爷'),
        (5, '奶奶'),
        (6, '外公'),
        (7, '外婆'),
        (12, '亲哥'),
        (13, '亲嫂'),
        (14, '表哥'),
        (15, '表嫂'),
        (16, '堂哥'),
        (17, '堂嫂'),
        (18, '亲姐'),
        (19, '亲姐夫'),
        (20, '表姐'),
        (21, '表姐夫'),
        (22, '堂姐'),
        (23, '堂姐夫'),
        (24, '伯父'),
        (25, '伯母'),
        (26, '叔父'),
        (27, '婶母'),
        (28, '舅父'),
        (29, '舅母'),
        (30, '姨父'),
        (31, '姨母'),
        (32, '姑父'),
        (33, '姑母'),
        (34, '其他亲属'),
        (35, '非亲属'),
    )


class stu_grades(models.Model):
    id = models.PositiveSmallIntegerField(verbose_name='年级', primary_key=True)
    name = models.CharField(max_length=50, verbose_name='年级名称')

    class Meta:
        verbose_name = '年级名称表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class stu_schools(models.Model):
    id = models.PositiveSmallIntegerField(verbose_name='学校编号', primary_key=True)
    name = models.CharField(max_length=50, verbose_name='学校名称')

    class Meta:
        verbose_name = '学校名称表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class stu_school_grade(models.Model):
    id = models.PositiveSmallIntegerField(verbose_name='序号', primary_key=True)
    school = models.ForeignKey(stu_schools, null=True, db_constraint=False,
                               related_name='schoolname', on_delete=models.SET_NULL)
    grade = models.ForeignKey(stu_grades, null=True, db_constraint=False, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = '学校年级名称总表'
        verbose_name_plural = verbose_name
        unique_together = ['school', 'grade']

    def __str__(self):
        return self.school.name + self.grade.name


class stu_register_table(models.Model):
    id = models.AutoField(
        primary_key=True)
    name = models.CharField(
        max_length=20, null=True, unique=False, verbose_name='学生姓名')
    card = models.CharField(
        max_length=18, null=True, unique=False, verbose_name='学生身份证号')
    age = models.IntegerField(
        null=True, verbose_name='年龄')
    schoolGrade = models.ForeignKey(
        stu_school_grade, null=True, db_constraint=False,
        on_delete=models.SET_NULL)
    jfr1name = models.CharField(
        max_length=20, null=True, unique=False, verbose_name='监护人1姓名')
    jfr1gx = models.PositiveSmallIntegerField(
        verbose_name='监护人1与登记人关系', choices=basiceduchoices.relations)
    jfr1tel = models.CharField(
        max_length=11, null=True, unique=False, verbose_name='监护人2联系电话')
    jfr2name = models.CharField(
        max_length=20, null=True, unique=False, verbose_name='监护人2姓名')
    jfr2gx = models.PositiveSmallIntegerField(
        verbose_name='监护人2与登记人关系',
        choices=basiceduchoices.relations, null=True)
    jfr2tel = models.CharField(
        max_length=11, null=True, unique=False, verbose_name='监护人2联系电话')
    regaddress = models.ForeignKey(
        region, null=True, db_constraint=False,
        on_delete=models.SET_NULL,
        related_name='reg', verbose_name='户籍所在地')
    resaddress = models.ForeignKey(
        region, null=True, db_constraint=False,
        on_delete=models.SET_NULL,
        related_name='res', verbose_name='居住所在地')
    resaddressnum = models.CharField(
        max_length=100, null=True, unique=False, verbose_name='居住地详细地址')
    stuobj = models.PositiveSmallIntegerField(
        verbose_name='登记对象属性', choices=basiceduchoices.stuobj)
    houseoption = models.PositiveSmallIntegerField(
        verbose_name='预登记学生现住房类型', choices=basiceduchoices.houseoptions)
    operatortype = models.IntegerField(
        '操作状态', default=0, choices=basiceduchoices.operator)
    publicid = models.IntegerField(
        '是否公示', default=0)

    class Meta:
        verbose_name = '预登记情况总表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class operation_stu_log(models.Model):
    card = models.CharField(
        max_length=18, null=True, unique=False, verbose_name='学生身份证号')
    edittype = models.IntegerField(
        '操作状态', default=0, choices=basiceduchoices.operator)
    names = models.CharField(
        max_length=11, null=True, unique=False, verbose_name='操作人')
    times = models.CharField(
        max_length=20, null=True, unique=False, verbose_name='操作时间')
    result = models.CharField(
        max_length=100, null=True, unique=False, verbose_name='操作结果')
    resultnotes = models.CharField(
        max_length=200, null=True, unique=False, verbose_name='操作情况补充说明')

    class Meta:
        verbose_name = '预登记情况操作日志'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.names


class infant_stu(models.Model):
    id = models.AutoField(
        primary_key=True)
    name = models.CharField(
        max_length=20, null=True, unique=False, verbose_name='学生姓名')
    card = models.CharField(
        max_length=18, null=True, unique=False, verbose_name='学生身份证号')
    age = models.IntegerField(
        '年龄')
    regaddress = models.CharField(
        max_length=100, null=True, unique=False, verbose_name='户籍所在地')
    resaddress = models.CharField(
        max_length=100, null=True, unique=False, verbose_name='居住所在地')
    regsch = models.CharField(
        max_length=100, null=True, unique=False, verbose_name='意向学校')
    tel = models.CharField(
        max_length=11, null=True, unique=False, verbose_name='联系电话')

    class Meta:
        verbose_name = '幼儿园入学意向调查表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

templates/elementary/publicity.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <title>划片</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <style>
body,
html,
#container {
  overflow: hidden;
  width: 100%;
  height: 100%;
  margin: 0;
  font-family: "微软雅黑";
}
    .drawing-panel {
      position: fixed;
      top: 1rem;
      margin-left: 1rem;
      padding: 1rem 1rem;
      border-radius: .25rem;
      background-color: #fff;
      box-shadow: 0 2px 6px 0 rgba(27, 142, 236, 0.5);
    }
    .drawing-search {
      position: fixed;
      top: 1rem;
      margin-left: 15rem;
      padding: 1rem 1rem;
      border-radius: .25rem;
      background-color: #fff;
      box-shadow: 0 2px 6px 0 rgba(27, 142, 236, 0.5);
    }
    </style>
    <script src="//api.map.baidu.com/api?type=webgl&v=2.0&ak=6gSs9txR5MrqAomoUlGGkIgQZrZthqPf"></script>
    <script type="text/javascript" src="/static/js/schoolmap.js"></script>
  </head>
  <body>
    <a href="/elementary/stu/index">点我返回首页</a><a id="msgbox"></a>
   <div class="drawing-search" style="z-index:88;"><input id="Address">
     <button  onclick="search()">查询</button></div>
    <div id="container"></div>
    <select class="drawing-panel" style="z-index:99;" onchange="schoolmap(value)">
      <option></option>
      <option value= "(1,104.47635,25.717453)">盘州市第一小学</option>
      <option value= "(2,104.468241,25.703617)">盘州市第二小学</option>
      <option value= "(3,104.485956,25.704848)">盘州市第三小学</option>
      <option value= "(4,104.490317,25.733002)">盘州市第四小学</option>
      <option value= "(5,104.412791,25.667041)">盘州市第五小学</option>
      <option value= "(6,104.520496,25.76219)">盘州市第六小学</option>
      <option value= "(8,104.465154,25.67995)">盘州市第八小学</option>
      <option value= "(9,104.484105,25.719809)">盘州市第九小学</option>
      <option value= "(10,104.469329,25.684679)">亦资街道红磷小学</option>
      <option value= "(11,104.435163,25.723347)">红果街道沙陀小学</option>
      <option value= "(12,104.486497,25.757979)">两河街道沙坡小学</option>
      <option value= "(21,104.461754,25.705824)">盘州市第八中学</option>
      <option value= "(22,104.49879,25.726349)">盘州市第十中学</option>
      <option value= "(23,104.452405,25.677084)">盘州市第十一中学</option>
      <option value= "(24,104.439414,25.728065)">红果街道沙陀中学</option>
     </select>
     <div class="drawing-panel" style="z-index:88;top:5rem;" id="map_result"></div>
  </body>
</html>
<script>
  var markerArr = [];
  var map = new BMapGL.Map('container');
  var point = new BMapGL.Point(104.4506313, 25.71539373);
  map.centerAndZoom(point, 17);
  map.enableScrollWheelZoom(true);
  map.addEventListener("click", changeLAT);
  function schoolmap(value,x,y) {
  map.enableScrollWheelZoom(true);
    //map.clearOverlays();
    var point = new BMapGL.Point(x,y);
    map.setCenter(point);
    var marker = new BMapGL.Marker(point); 
    map.addOverlay(marker); 
    map.addOverlay(eval("schoolmap" + value));
    }
  function search(){
  map.centerAndZoom(point, 17);
      map.enableScrollWheelZoom();
      map.enableContinuousZoom();  
      getAddress();}
  function getAddress() {
    var address =document.getElementById("Address").value;
    var myGeo = new BMapGL.Geocoder();
    myGeo.getPoint(address, function (point) {
    if (point) {
      map.centerAndZoom(point, 17);
      var marker = new BMapGL.Marker(point);
      map.addOverlay(marker);
      var local = new BMapGL.LocalSearch(map, {
	  renderOptions: { map: map, panel: "map_result" }
      });
      local.search(address)
    } else { alert("您选择地址没有解析到结果!"); }
    }, "盘州市");
  }
  function changeLAT(e) {
    //  alert(e.point.lng + ", " + e.point.lat);
      if(markerArr.length != 0){
	  map.removeOverlay(markerArr[0]);
	  markerArr=[];
	}
    longitude= e.latlng.lng; latitude= e.latlng.lat;
    var marker = new BMapGL.Marker(new BMapGL.Point(longitude, latitude));
      var latlngtext= "经度：" + longitude + "<br />  纬度：" + latitude;
    var label = new BMapGL.Label(latlngtext, { offset: new BMapGL.Size(20, -10) });
    marker.setLabel(label);
    markerArr.push(marker); map.addOverlay(marker);
  }
</script>

templates/elementary/review_stu_info.html
{%extends "base.html" %}
{%load static %}
{% block mainbody %}
<div id="main" data-options="region:'center'" style="width:100%;height:100%;">
  <p>学生基本信息</p>
  <table id="stuinfo">
    <tr>
      <td>学生姓名</td><td>{{data.0.name}}</td>
      <td>登记学校</td><td>{{data.0.schoolGrade}}</td>
    </tr>
    <tr>
      <td>与监护人员1关系</td> <td>{{data.0.get_jfr1gx_display}}</td>
      <td>监护人员1姓名</td> <td>{{data.0.jfr1name}}</td>
      <td>监护人员1电话</td> <td>{{data.0.jfr1tel}}</td>
    </tr>
    <tr>
      <td>与监护人员2关系</td> <td>{{data.0.get_jfr2gx_display}}</td>
      <td>监护人员2姓名</td> <td>{{data.0.jfr2name}}</td>
      <td>监护人员2电话</td> <td>{{data.0.jfr2tel}}</td>
    </tr>
    <tr>
      <td>户籍所在地</td> <td colspan="5">{{data.0.regaddress.addressAll}}</td>
    </tr>
    <tr>
      <td>现居住地址</td> <td colspan="5">{{data.0.resaddress.addressAll}}</td>
    </tr>
    <tr>
      <td>现住房类型</td> <td>{{data.0.get_houseoption_display}}</td>
      <td>学生年龄</td> <td>{{data.0.age}}</td>
      <td>身份证号</td> <td>{{data.0.card}}</td>
    </tr>
    <tr>
      <td>登记属性</td> <td colspan="3">{{data.0.get_stuobj_display}}</td>
      <td>审核状态</td> <td><font color="red">{{data.0.get_operatortype_display}}</font></td>
    </tr>
  </table>
  <div id="operatorResult">	{% csrf_token %}
    <p>审核<sub>初审不通过:非申报范围不驳回,用户无法修改，直接审核不通过，流程结束。</sub></p>
    审核结果：
    {% if request.user.last_name == '0' %} 
    <select id="operator" class="easyui-combobox" style="width:200px;">
      <option value="4">驳回修改</option>
      <option value="5">复审通过</option>
      <option value="6">复审不通过</option>
    </select>
    {% else %} 
    <select id="operator" class="easyui-combobox" style="width:200px;">
      <option value="4">审核不通过（驳回修改）</option>
      <option value="2">初审通过</option>
      <option value="3">初审不通过（不允许再次提交）</option>
    </select>
    {% endif %} 
    审核补充意见：
    <select id="operatortype" class="easyui-combobox" style="width:500px;">
    <option></option>
    <option>户籍所在地不在我校招生范围，请以实际符合的相应类型填报</option>
    <option>不在我校服务划片范围内</option>
    <option>学生家长请求驳回修改</option>
    <option>上传资料不完整</option>
    <option>上传资料不清晰</option>
    <option>上传资料无效</option>
    <option>房屋地址或购房人不详，请补充相关材料</option>
    <option>不属于填报范围内人员</option>
    <option>房主与就读孩子的关系不明，请上传结婚证或出生证等能证明房主与孩子关系的证明材料</option>
    <option>证明类材料未加盖相关单位公章，无法印证材料真实性</option>
    <option>证明类材料页数不全，存在缺失关键页情况</option>
    <option>合同类材料未加盖相关单位公章，无法印证材料真实性</option>
    <option>合同类材料页数不全，存在缺失关键页情况</option>
    <option>登记属性填写错误</option>
    <option>不是适龄范围，年龄错误！审核不通过（不允许再次提交）</option>
  </select>
    <a href="javascript:void(0)" class="easyui-linkbutton" style="" onclick="submitForm()">提交审核结果</a>
  </div>
  <p>材料上传情况<sub>温馨提示：单击缩略图即可看到原始图像！</sub></p>
  <table id="images">
    <tr><td>材料名称</td><td>缩略图</td> <td>材料名称</td><td>缩略图</td> <td>材料名称</td><td>缩略图</td> <td>材料名称</td><td>缩略图</td>
    </tr>
    <tr>
      <td>*户口籍首页 </td>
      <td><a onclick="stuExamineImage(1)"><img id="img1" src="/static/stuimage/{{data.0.card}}/1_1x.jpg" onerror="nofind()"></a></td>
      <td>*监护人员1页</td>
      <td><a onclick="stuExamineImage(2)"><img id="img2" src="/static/stuimage/{{data.0.card}}/2_1x.jpg" onerror="nofind()"></a></td>
      <td>监护人员2页</td>
      <td><a onclick="stuExamineImage(3)"><img id="img3" src="/static/stuimage/{{data.0.card}}/3_1x.jpg" onerror="nofind()"></a></td>
      <td>*学生本页</td>
      <td><a onclick="stuExamineImage(4)"><img id="img4" src="/static/stuimage/{{data.0.card}}/4_1x.jpg" onerror="nofind()"></a></td>
    <tr><td>{{imagename.0}}</td>
      <td><a onclick="stuExamineImage(5)"><img id="img5" src="/static/stuimage/{{data.0.card}}/5_1x.jpg" onerror="nofind()"></a></td>
      <td>{{imagename.1}}</td>
      <td><a onclick="stuExamineImage(6)"><img id="img6" src="/static/stuimage/{{data.0.card}}/6_1x.jpg" onerror="nofind()"></a></td>
      <td>{{imagename.2}}</td>
      <td><a onclick="stuExamineImage(7)"><img id="img7" src="/static/stuimage/{{data.0.card}}/7_1x.jpg" onerror="nofind()"></a></td>
      <td>其他证明或补充页</td>
      <td><a onclick="stuExamineImage(8)"><img id="img8" src="/static/stuimage/{{data.0.card}}/8_1x.jpg" onerror="nofind()"></a></td>
    </tr>
  </table>
  <div>
    <p>操作日志</p>
    <table id="log">
      <tr>
        <td>序号</td>
        <td>操作人</td>
        <td>当前状态</td>
        <td>操作类型</td>
        <td colspan="3">操作情况补充说明</td>
        <td>操作时间</td>
      </tr>
      {% for item in log %}
<tr>
        <td>{{forloop.counter}}</td>
        <td>{{item.names}}</td>
        <td>{{item.get_edittype_display}}</td>
        <td>{{item.result}}</td>
        <td colspan="3">{{item.resultnotes}}</td>
        <td>{{item.times}}</td>
      </tr>
      {% endfor %}
    </table>
  </div>
</div>
<style>
img {height:160px;width:100px;}
#images tr td { border:1px solid #000000;width:120px; }
#stuinfo tr td { border:1px solid #000000;width:160px; }
#operatorTable tr td { border:1px solid #000000;width:160px; }
#log td { border:1px solid #000000;width:120px; }
table { text-align: center; border-collapse: collapse; padding:2px;}
</style>
<script>
function submitForm(){
let operatortext=$("#operator").combobox("getText");
let operator=$("#operator").val();
let operatortype=$("#operatortype").combobox("getText");
if(operator=='4' && operatortype.length<=5){
alert("必须填写驳回理由!");
}else{
$.messager.confirm('当前学生：{{data.0.name}}',"你当前选择的学生是“{{data.0.name}}”,审核结果为：“" + operatortext + '”,确认提交吗？',function(r){
if (r){
$.ajax({url:"",
type:'POST',
data:{"card":"{{data.0.card}}",
"operator":operator,
"operatortype":operatortype,
'csrfmiddlewaretoken': $('input[name="csrfmiddlewaretoken"]').val()
},
success:function(result){
alert(result.msg);
reload();
}
});
}
});//.panel('move',{left:220,top:280});
}}
</script>
<script>
$(function(){
let stuobj={{data.0.stuobj}};
if(stuobj==1){ $("#img7").hide();$("#img5").hide();$("#img6").hide();$("#img7").hide();}
else if(stuobj==4){$("#img7").hide();}
else if(stuobj==5){$("#img7").hide();}
else if(stuobj==6){$("#img6").hide();$("#img7").hide();}
});
function nofind(){
var img=event.srcElement;
img.src="{% static 'elementary/error.jpg'%}"; //替换的图⽚
img.onerror=null; //控制不要⼀直触发错误
}
</script>
<script>
function stuExamineImage(value){
window.open("SeeImage?card={{data.0.card}}", 'newwindow', 'width='+ (screen.availWidth - 10) +',height='+ (screen.availHeight-50) +',top=0, left=0, toolbar=no, menubar=no, scrollbars=no, resizable=no, location=no, status=no')  
}
</script>
{% endblock %}

templates/elementary/stu_query_register.html
{%extends "base.html" %}
{%load static %}
{% block mainbody %}
<div id="main" data-options="region:'center',title:'预登记情况总表'" style="width:100%;height:100%;">
  <div>
    <h3>当前学生：{{data.0.name}}&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
    学生年龄：{{data.0.age}}岁&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
    预报名登记学校名称：{{data.0.schoolGrade}}&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
    </h3>
    <h3>
    与监护人员1关系：{{data.0.get_jfr1gx_display}}&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
    监护人员1姓名：{{data.0.jfr1name}}&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
    监护人员1联系电话：{{data.0.jfr1tel}}&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
    </h3>
    <h3>
    与监护人员2关系：{{data.0.get_jfr2gx_display}}&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
    监护人员2姓名：{{data.0.jfr2name}}&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
    监护人员2联系电话：{{data.0.jfr2tel}}&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
    </h3>
    <h3>
    户籍所在地：{{data.0.regaddress.addressAll}}&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
    现居住地址：{{data.0.resaddress.addressAll}}&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
    </h3>
    <h3>
    住房类型：{{data.0.get_houseoption_display}}&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
    学生身份证号：{{data.0.card}}&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
    登记属性：{{data.0.get_stuobj_display}}&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
    </h3>
    <h1 style="color:red;">
    现审核状态：{{data.0.get_operatortype_display}}&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
    </h1>
  </div>
    <table id="images">
      <tr><td>材料名称</td><td>缩略图</td> <td>材料名称</td><td>缩略图</td> <td>材料名称</td><td>缩略图</td> <td>材料名称</td><td>缩略图</td>
      </tr>
      <tr>
	<td>*户口籍首页 </td>
	<td><img id="img1" src="/static/stuimage/{{data.0.card}}/1_1x.jpg" onerror="nofind()"></td>
	<td>*监护人员1页</td>
	<td><img id="img2" src="/static/stuimage/{{data.0.card}}/2_1x.jpg" onerror="nofind()"></td>
	<td>监护人员2页</td>
	<td><img id="img3" src="/static/stuimage/{{data.0.card}}/3_1x.jpg" onerror="nofind()"></td>
	<td>*学生本页</td>
	<td><img id="img4" src="/static/stuimage/{{data.0.card}}/4_1x.jpg" onerror="nofind()"></td></tr>
      <tr><td>{{imagename.0}}</td>
	<td><img id="img5" src="/static/stuimage/{{data.0.card}}/5_1x.jpg" onerror="nofind()"></td>
	<td>{{imagename.1}}</td>
	<td><img id="img6" src="/static/stuimage/{{data.0.card}}/6_1x.jpg" onerror="nofind()"></td>
	<td>{{imagename.2}}</td>
	<td><img id="img7" src="/static/stuimage/{{data.0.card}}/7_1x.jpg" onerror="nofind()"></td>
	<td>其他证明或补充页</td>
	<td><img id="img8" src="/static/stuimage/{{data.0.card}}/8_1x.jpg" onerror="nofind()"></td>
	  </tr>
    </table>
    <div>
      <h1>操作日志</h1>
      <table id="log">
	<tr>
	  <td>序号</td>
	  <td>操作人</td>
	  <td>当前状态</td>
	  <td>操作类型</td>
	  <td>操作情况补充说明</td>
	  <td>操作时间</td>
	</tr>
	{% for item in log %}
	<tr>
	  <td>{{forloop.counter}}</td>
	  <td>{{item.names}}</td>
	  <td>{{item.get_edittype_display}}</td>
	  <td>{{item.result}}</td>
	  <td>{{item.resultnotes}}</td>
	  <td>{{item.times}}</td>
	</tr>
	{% endfor %}
      </table>
    </div>
</div>
<style>
  img {height:160px;width:100px;}
  #images tr td { border:1px solid #0094ff;width:120px; }
  #log td { border:1px solid #0094ff;width:160px; }
  table { text-align: center; border-collapse: collapse; padding:2px;}
</style>
<script>
  $(function(){
      let stuobj={{data.0.stuobj}};
      if(stuobj==1){ $("#img7").hide();$("#img5").hide();$("#img6").hide();$("#img7").hide();}
      else if(stuobj==4){$("#img7").hide();}
      else if(stuobj==5){$("#img7").hide();}
      else if(stuobj==6){$("#img6").hide();$("#img7").hide();}
    });
function nofind(){
  var img=event.srcElement;
    img.src="{% static 'elementary/error.jpg'%}"; //替换的图⽚
  img.onerror=null; //控制不要⼀直触发错误
}
</script>
{% endblock %}